### ISSUE TITLE
iOS can't add new child/parent nodes

### ISSUE THREAD

**Issue by sj-franklin-maine** [owenbean400/RecipeRootsApp#8]

**Comment by owenbean400** [comment]
@sj-franklin-maine Where are you finding this issue? What build and server? In demo I was able to do it...

**Comment by owenbean400** [comment]
@sj-franklin-maine Did you delete the app when we had table change from family_tree to child_to_parent? The table could have not been created because no schema update was made because the app is not live to the public. Only you, I, and Shea had the app beforehand.
